config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  # Github OAutch connection
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Github Auth Stuff
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_github_user_session
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_github_user_session
    #get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_github_user_session
  end

  get 'pages' => 'pages#search'

  root to: 'pages#home'


  resources :profiles, only: [:show, :create, :update] do
    resources :profile_technologies, only: [:new, :create, :destroy]
    resources :user_follows, only: [:create, :update]
    resources :projects, only: [ :update, :create] do
      resources :contributions, only: [:destroy]
    end
  end

  resources :projects, only: [:show, :destroy] do
    resources :project_technologies, only: [:new, :create, :destroy]
    resources :project_follows, only: [:new, :create, :destroy]
  end



end

app/models/user.rb
require 'json'
require 'open-uri'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github]
  has_one :profile

  after_create :link_github


  # Need an after create method that updates the data of the corresponding profile with the inputted values from the github OAuth

  # Method to add a project that is not in someones repos manually
  def add_project(url, github_type)
    inputted_url = url
    inputted_github_type = github_type
    AddProject.new(self.profile, inputted_url, inputted_github_type)
  end

  # Github Authentication Method
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.full_name = auth.info.name   # assuming the user model has a name
    user.profile_photo = auth.info.image  # assuming the user model has an image
    user.github_username = auth.info.nickname
    user.github_id = auth.uid

    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end

  private

  def link_github
    profile = Profile.find_by(github_username: self.github_username)
    if profile
      profile.user = self
    else
      profile = Profile.new(github_username: self.github_username)
      profile.user = self
    end
    profile.save
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end

  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]



  def new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.create(username: params[:username], email: "#{params[:username]}@gmail.com", password: 'password')
    redirect_to root_path
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end

end

app/views/users/show.html.erb
<div class="wrapper">
  <div class="card-outer">
    <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-1">
            <div class="box-1">
              <div class="card-image" style=" background: url('<%= image_path "image-desk.jpg" %>'); background-size: cover; background-position: center; ">
              </div>
            </div>
          </div>
        </div>

        <div class="col-xs-12  col-sm-6 col-md-4">
          <div class="card-2" >
            <div class="box-2">
              <div class="h3">Project title!</div>
              <div class="text-field">

                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur consequatur optio, illum sed! Libero totam aliquam, eum, excepturi esse reiciendis magnam nemo! Nesciunt saepe veritatis quae, ea doloremque explicabo architecto. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur consequatur optio, illum sed! Libero totam aliquam, eum, excepturi esse reiciendis magnam nemo! Nesciunt saepe veritatis quae, ea doloremque explicabo architecto.
              </div>
            </div>
          </div>
        </div>

        <div class="col-xs-12  col-sm-12 col-md-4">
          <div class="card-3 ">
            <div class="box-3">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae laborum enim obcaecati at quibusdam, voluptate quasi voluptas eos ad quas cupiditate, magnam! Ipsam totam quam, accusantium officia, obcaecati quidem sint.
            </div>
         </div>
       </div>

     </div>
   </div>
</div>

app/views/users/show_backup.html.erb
<div class="wrapper">
  <div class="container">

    <div class="card-outer">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="card-section card-section-1">
            <div class="card-image" style=" background: url('<%= image_path "image-desk.jpg" %>'); background-size: cover; background-position: center; ">
            </div>
            </div>
        </div>
        <div class="col-xs-12  col-sm-6 col-md-4">
          <div class="card-section card-section-2" >
            <div class="project-description">
              <p>This is a paragraph of text that will be the descfription of the project that this card is for.Hoefull that is obvious by looking at this. This is a paragraph of text that will be the descfription of the project that this card is for.Hoefull that is obvious by looking at this.This is a paragraph of text that will be the descfription of the project that this card is for.Hoefull that is obvious by looking at this. This is a paragraph of text that will be the descfription of the project that this card is for.Hoefull that is obvious by looking at this</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12  col-sm-12 col-md-4">
          <div class="card-section card-section-3 ">
            <div class="stats-box">
             <p>This is a paragraph of text that will be the descfription of the project that this card is for.Hoefull that is obvious by looking at this. This is a paragraph of text that will be the descfription of the project that this card is for.Hoefull that is obvious by looking at this.</p>
           </div>
         </div>
       </div>
     </div>
   </div>


<h1>#<%= User.find(1).email %></h1>
  <p> <%=link_to "Back Home", root_path %></p>
  <p> <%= link_to "Go to a user show page", user_path(1) %></p>
  <p> <%=link_to "Go to a project page", project_path(1) %></p>
</div>
</div>