config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  # Github OAutch connection
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Github Auth Stuff
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_github_user_session
    # get 'sign_in', :to => 'devise/sessions#new', :as => :new_github_user_session
    #get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_github_user_session
  end

  get 'pages' => 'pages#search'

  root to: 'pages#home'


  resources :profiles, only: [:show, :create, :update] do
    resources :profile_technologies, only: [:new, :create, :destroy]
    resources :user_follows, only: [:create, :update]
    resources :projects, only: [ :update, :create] do
      resources :contributions, only: [:destroy]
    end
  end

  resources :projects, only: [:show, :destroy] do
    resources :project_technologies, only: [:new, :create, :destroy]
    resources :project_follows, only: [:new, :create, :destroy]
  end



end

app/views/shared/_biocards.html.erb
<div class="biocards-container">
  <div class="row">


      <div class="bio-left col-xs-12 col-sm-6">

        <div class="bio-flex">
          <div class="bio-flex-item1">

            <div class="biobox biobox-1 box-shadow-os">
              <div class="biobox-content">
                <div class="bio-title">Github username</div>
                <strong><%= link_to "https://github.com/#{@profile.github_username}" do %>

                  <%= @profile.github_username %>
                  <i id="ghub" class="fab fa-github fa-2x biocards-git-icon"></i>

                <% end %></strong>

             </div>
           </div>

            <div class="biobox biobox-4 box-shadow-os">
              <div class="biobox-content">
                <div class="bio-title">Top language</div>

                <% unless @profile.top_languages == [] %>
                <div><strong><%= @profile.top_languages.first[0].capitalize %></strong></div>
                <% end %>
            </div>
          </div>
        </div>

        <div class="bio-flex-item2">
          <div class="biobox biobox-2  box-shadow-os">
            <div class="biobox-content">
              <div class="bio-title">Total commits</div>
              <div><strong><%= @profile.total_contributions[:commits] %></strong></div>

            </div>
          </div>

          <div class="biobox biobox-3 box-shadow-os">
             <div class="biobox-content">
            <div class="bio-title">No. of Projects</div>
            <div><strong><%= @profile.repo_number %></strong></div>
          </div>
          </div>
        </div>

        </div>
      </div>


    <div class="bio-right col-xs-12 col-sm-6">
      <div class="topl-container box-shadow-os">
<!--         <div class="tolp-title text-center">
          Top Language
        </div> -->
        <div class="topl-graph text-center">
          <%= render 'shared/top_languages' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_com-ovr-time.html.erb
  <% commits_per_week = profile.commits_per_week_in_a_year(2018) %>
  <% unless commits_per_week %>
    <img src="https://media.giphy.com/media/joV1k1sNOT5xC/giphy.gif" alt="">
  <% else %>
    <canvas id="comovert-chart" class="js-comovert-chart" data-year-array="<%= commits_per_week[:year_array] %>" data-comovertchartlabeldata="<%= commits_per_week.except(:year_array).to_json %>""></canvas>
  <% end %>

app/views/shared/_create_project_modular.html.erb
<!-- Create Project from User input -->

<!-- Button trigger modal -->
<div class="project-edit-icon">
  <button type="button" class="btn btn-primary btn-lg add-a-project-btn" data-toggle="modal" data-target="#project-form-<%= @project.id %>">
  Import project</button>
  <!-- Modal -->
  <div class="modal fade" id="project-form-<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Import a Project you contriuted to</h4>
        </div>

        <form action="<%= profile_projects_path(profile) %>" method="POST">
          <div class="modal-body">

            <div class="form-group">

              <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

              <label class="form-control-label string optional" for="url">Input the repositories URL</label>
              <input class="form-control" name="url" type="text" placeholder="Example: https://github.com/Skyrmo/rails-mister-cocktail"></input>
            </div>

            <div class="form-group">
              <label class="form-control-label string optional" for="url">Who is the owner of the repository?</label>

              <div class="form-check">

                <input class="form-check-input" id="exampleRadios1" name="github_type" type="radio" value="users" checked> </input>
                <label class="form-control-label string optional" for="users">Private user (e.g. hilmarx)</label>

              </div>

              <div class="form-check">

                <input class="form-check-input" id="exampleRadios1" name="github_type" type="radio" value="orgs"> </input>
                <label class="form-control-label string optional" for="users">Organization (e.g. Microsoft)</label>

              </div>

            </div>
          </div>


          <div class="modal-footer">

            <button type="submit" class="btn btn-primary">Submit
            </button>

          </div>

        </form>



      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_github-photo.html.erb
<div class="profile-img profile-photo" style="background-image: url('<%= cl_image_path profile.profile_photo %>');">

  <% if @profile.user && @profile.user == current_user %>
  <div id="profile-img-hover" class="text-center">
      <%= render 'shared/photo-upload-form'%>
      <% end %>
  </div>
</div>

app/views/shared/_jethro_follow_button.html.erb
<% if current_user %>
  <% if @profile.user %>
    <% if @profile.user != current_user %>
      <% @user_follow = UserFollow.find_instance(@profile, current_user) %>
      <% if @user_follow %>
        <% if @user_follow.status == true %>
          <%= link_to(profile_user_follow_path(@profile, @user_follow), method: :patch, class: 'btn btn-success') do %>
              Unfollow <%= @profile.full_name %>
          <% end %>
        <% else %>
          <%= link_to(profile_user_follow_path(@profile, @user_follow), method: :patch, class: 'btn btn-primary') do %>
            Follow <%= @profile.full_name %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to(profile_user_follows_path(@profile), method: :post, class: 'btn btn-primary') do %>
          Follow <%= @profile.full_name %>
        <% end %>
      <% end %>
    <% else %>
      <!-- <p class="btn btn-warning">You can't follow your own profile 😋</p> -->
    <% end %>
  <% else %>
    <!-- <p class="btn btn-danger">Invite <%#= @profile.github_username %> to BUIDL</p> -->
  <% end %>
<% else %>
  <%= link_to "Follow", user_github_omniauth_authorize_path,  class: 'btn btn-primary' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon fix-to-top sticky">


  <div class="nav-left">

      <%= link_to root_path, class: "navbar_logo logo_font" do %>
      <%= image_tag 'Frame.png', class: "logo-image" %>
      <div class="text-logo">Buidl</div>
      <% end %>
  </div>

  <!-- Right Navigation -->

  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

        <!-- Jethro code --->
        <%# if @profile %>
          <%#= cl_image_tag @profile.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <%# else %>
          <%#= image_tag('logo.png', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>
        <%# end %>
        <!-- Jethro code END --->



          <% if current_user.profile.photo.present? %>
          <%= cl_image_tag current_user.profile.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag current_user.profile_photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to profile_path(current_user.profile) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>


      </div>
    </div>
    <% else %>

    <!-- Sign in with Github -->
    <%= link_to "Claim your profile", user_github_omniauth_authorize_path, class: "navbar-wagon-item navbar-wagon-link btn" %>
    <!--Sign in with github end -->
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">


    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to profile_path(current_user.profile) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
          </li>
        <% else %>
          <li><%= link_to "Sign in with Github", user_github_omniauth_authorize_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
          <li><%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_photo-upload-form.html.erb
<% if policy(@profile).update? %>
  <%= simple_form_for(@profile) do |f| %>
    <!-- [...] -->
    <label class= 'form-control-label string optional' for="profile_photo"></label>
    <%= f.input :photo, label: false, input_html: {style: 'display: none'}  %>
    <%= f.input :photo_cache, as: :hidden %>
    <p>Change photo</p>

    <a href="#" class='btn' id='upload-fake-btn'><i class="fas fa-edit"></i></a>
    <%= submit_tag "", :style => "display: none;" %>
  <% end %>
<% end %>

app/views/shared/_photo_upload.html.erb
<%= simple_form_for(@profile) do |f| %>
  <!-- [...] -->
  <label class= 'form-control-label string optional' for="profile_photo"></label>
  <%= f.input :photo, label: false, input_html: {style: 'display: none'}  %>
  <%= f.input :photo_cache, as: :hidden %>
  <p>Change your photo</p>

  <a href="#" class='btn' id='upload-fake-btn'><i class="fas fa-edit"></i></a>
  <%= submit_tag "", :style => "display: none;" %>
<% end %>

app/views/shared/_profile-photo.html.erb
<div class="profile-img profile-photo" style="background-image: url('<%= cl_image_path profile.photo %>');">

<% if @profile.user && @profile.user == current_user %>
  <div id="profile-img-hover" class="text-center">
      <%= render 'shared/photo-upload-form'%>
  </div>
  <% end %>

</div>

app/views/shared/_project_card.html.erb
<div class="card-outer box-shadow-os">
  <div class="row">

    <div class="col-xs-12 col-sm-6">
      <div class="card-2" >

        <div class="box-2">

          <div class="title-box">
            <div class="h3 project-card-title">
              <%= project.kebab_convert(project.name) %>
            </div>
          </div>

          <div class="desc-box">
            <div class="text-field">
              <% if project.description.nil? %>
                <%= project.github_description %>
              <% else %>
                <%= project.description %>
              <% end %>
            </div>
          </div>

          <div class="p-lang">
            <div class="h5">Primary language:</div>
            <div class="h5 primary-language">
              <%= project.primary_language %>
            </div>
          </div>

          <div class="edit-btn-wrapper">
            <!-- Input edit button here -->
            <% if profile.user && profile.user == current_user %>
            <%= render "shared/update_project_modal", project: project, profile: profile %>
            <% end %>
            <!-- End Input Button -->
          </div>



        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <div class="card-3 ">
        <div class="box-3">

          <div class="lang-data">
            <div class="tech-container">
              <div class="h5 text-center">Project Technologies</div>
              <ul>
                <% chartLabelData = {} %>

                <% project.project_technologies.each do |pro_tech| %>
                  <% technology = Technology.find(pro_tech.technology_id).name %>
                  <% chartLabelData[technology] = pro_tech.size_bytes %>
                  <li>
                    <%#= technology %> <%#= pro_tech.size_bytes %>
                  </li>
                <% end %>

                <% chartLabelData = chartLabelData.to_json %>
              </ul>

              <div class="chart-container"  style="width:250px; height:250px;">
                <canvas id="product-chart-<%= project.id %>" class="js-product-chart" data-chartlabeldata="<%= chartLabelData %>" data-projectid="<%= project.id %>"></canvas>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_top_languages.html.erb
<div class="graph-div">
    <div class="toplgraph">

      <% toplchartLabelData = {} %>

      <% @profile.top_languages.each do |lang| %>
        <% technology = lang[0] %>
        <% toplchartLabelData[technology] = lang[1] %>
        <% toplchartLabelData  %>
      <% end %>

      <% toplchartLabelData = toplchartLabelData.to_json %>

      <div id="chart-container">
      <canvas id="top-lang-chart" class="toplang-chart" data-toplchartlabeldata="<%= toplchartLabelData %>"</canvas>
      </div>
    </div>
  </div>
</div>

app/views/shared/_update_project_modal.html.erb
<!-- Edit Projects description and name -->

<!-- Button trigger modal -->
<div class="project-edit-icon">
<div type="button" class="edit-btn" data-toggle="modal" data-target="#project-form-<%= project.id %>">
  <i class="fa fa-edit"></i>
</div>
<!-- Modal -->
<div class="modal fade" id="project-form-<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit <%= project.kebab_convert(project.name) %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@profile, project] do |f| %>
          <!--<label class= 'edit-projectx' for="profile_photo">Titel</label>-->
          <%= f.input :name%>
         <!-- <label class= 'edit-projectx' for="profile_photo">Description</label>--->
          <%= f.input :description, as: :text%>

      </div>
      <div class="modal-footer">

        <!-- Delete this project button -->
        <!-- Delete all contribtuions associated with this project -->
        <%= link_to "Delete this project", profile_project_contribution_path(@profile.id, project.id, @profile.contributions.first), method: :delete, class: "btn btn-danger" %>
        <!-- Delete this project button -->

        <!-- Submit button -->
        <%= f.submit :class => "btn btn-primary" %>
        <!-- End Submit button -->
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>